[package]
name = "websocket-guest-provider"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = { workspace = true }
getrandom = "0.3"
url = "2"
wit-bindgen = { workspace = true, features = ["async", "async-spawn", "inter-task-wakeup"] }

[lints.rust]
missing_docs = "warn"
